// Package sequencer provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.15.0 DO NOT EDIT.
package sequencer

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

// Defines values for CreateBridgeEntryDtoIssuingChainType.
const (
	CreateBridgeEntryDtoIssuingChainTypeEvm CreateBridgeEntryDtoIssuingChainType = "evm"
	CreateBridgeEntryDtoIssuingChainTypeXrp CreateBridgeEntryDtoIssuingChainType = "xrp"
)

// Defines values for CreateBridgeEntryDtoLockingChainType.
const (
	CreateBridgeEntryDtoLockingChainTypeEvm CreateBridgeEntryDtoLockingChainType = "evm"
	CreateBridgeEntryDtoLockingChainTypeXrp CreateBridgeEntryDtoLockingChainType = "xrp"
)

// CreateBridgeEntryDto defines model for CreateBridgeEntryDto.
type CreateBridgeEntryDto struct {
	Id                                      string                               `json:"id"`
	IssuingChainDoorCreateBridgeTransaction string                               `json:"issuingChainDoorCreateBridgeTransaction"`
	IssuingChainType                        CreateBridgeEntryDtoIssuingChainType `json:"issuingChainType"`
	LockingChainDoorCreateBridgeTransaction string                               `json:"lockingChainDoorCreateBridgeTransaction"`
	LockingChainType                        CreateBridgeEntryDtoLockingChainType `json:"lockingChainType"`
}

// CreateBridgeEntryDtoIssuingChainType defines model for CreateBridgeEntryDto.IssuingChainType.
type CreateBridgeEntryDtoIssuingChainType string

// CreateBridgeEntryDtoLockingChainType defines model for CreateBridgeEntryDto.LockingChainType.
type CreateBridgeEntryDtoLockingChainType string

// SignBridgeEntryRequest defines model for SignBridgeEntryRequest.
type SignBridgeEntryRequest struct {
	SignedIssuingChainDoorCreateBridgeTransaction SignedTransactionRequest `json:"signedIssuingChainDoorCreateBridgeTransaction"`
	SignedLockingChainDoorCreateBridgeTransaction SignedTransactionRequest `json:"signedLockingChainDoorCreateBridgeTransaction"`
}

// SignedTransactionRequest defines model for SignedTransactionRequest.
type SignedTransactionRequest struct {
	Account   string `json:"account"`
	PublicKey string `json:"publicKey"`
	Signature string `json:"signature"`
}

// SignCreateBridgeJSONRequestBody defines body for SignCreateBridge for application/json ContentType.
type SignCreateBridgeJSONRequestBody = SignBridgeEntryRequest

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetHello request
	GetHello(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// SignCreateBridgeWithBody request with any body
	SignCreateBridgeWithBody(ctx context.Context, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	SignCreateBridge(ctx context.Context, id string, body SignCreateBridgeJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetCreateBridge request
	GetCreateBridge(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetHello(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetHelloRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) SignCreateBridgeWithBody(ctx context.Context, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSignCreateBridgeRequestWithBody(c.Server, id, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) SignCreateBridge(ctx context.Context, id string, body SignCreateBridgeJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSignCreateBridgeRequest(c.Server, id, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetCreateBridge(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetCreateBridgeRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetHelloRequest generates requests for GetHello
func NewGetHelloRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewSignCreateBridgeRequest calls the generic SignCreateBridge builder with application/json body
func NewSignCreateBridgeRequest(server string, id string, body SignCreateBridgeJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewSignCreateBridgeRequestWithBody(server, id, "application/json", bodyReader)
}

// NewSignCreateBridgeRequestWithBody generates requests for SignCreateBridge with any type of body
func NewSignCreateBridgeRequestWithBody(server string, id string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/sequencer/create-bridge/sign/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetCreateBridgeRequest generates requests for GetCreateBridge
func NewGetCreateBridgeRequest(server string, id string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/sequencer/create-bridge/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetHelloWithResponse request
	GetHelloWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetHelloResponse, error)

	// SignCreateBridgeWithBodyWithResponse request with any body
	SignCreateBridgeWithBodyWithResponse(ctx context.Context, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*SignCreateBridgeResponse, error)

	SignCreateBridgeWithResponse(ctx context.Context, id string, body SignCreateBridgeJSONRequestBody, reqEditors ...RequestEditorFn) (*SignCreateBridgeResponse, error)

	// GetCreateBridgeWithResponse request
	GetCreateBridgeWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*GetCreateBridgeResponse, error)
}

type GetHelloResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r GetHelloResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetHelloResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type SignCreateBridgeResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r SignCreateBridgeResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r SignCreateBridgeResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetCreateBridgeResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *CreateBridgeEntryDto
}

// Status returns HTTPResponse.Status
func (r GetCreateBridgeResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetCreateBridgeResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetHelloWithResponse request returning *GetHelloResponse
func (c *ClientWithResponses) GetHelloWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetHelloResponse, error) {
	rsp, err := c.GetHello(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetHelloResponse(rsp)
}

// SignCreateBridgeWithBodyWithResponse request with arbitrary body returning *SignCreateBridgeResponse
func (c *ClientWithResponses) SignCreateBridgeWithBodyWithResponse(ctx context.Context, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*SignCreateBridgeResponse, error) {
	rsp, err := c.SignCreateBridgeWithBody(ctx, id, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSignCreateBridgeResponse(rsp)
}

func (c *ClientWithResponses) SignCreateBridgeWithResponse(ctx context.Context, id string, body SignCreateBridgeJSONRequestBody, reqEditors ...RequestEditorFn) (*SignCreateBridgeResponse, error) {
	rsp, err := c.SignCreateBridge(ctx, id, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSignCreateBridgeResponse(rsp)
}

// GetCreateBridgeWithResponse request returning *GetCreateBridgeResponse
func (c *ClientWithResponses) GetCreateBridgeWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*GetCreateBridgeResponse, error) {
	rsp, err := c.GetCreateBridge(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetCreateBridgeResponse(rsp)
}

// ParseGetHelloResponse parses an HTTP response from a GetHelloWithResponse call
func ParseGetHelloResponse(rsp *http.Response) (*GetHelloResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetHelloResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseSignCreateBridgeResponse parses an HTTP response from a SignCreateBridgeWithResponse call
func ParseSignCreateBridgeResponse(rsp *http.Response) (*SignCreateBridgeResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &SignCreateBridgeResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseGetCreateBridgeResponse parses an HTTP response from a GetCreateBridgeWithResponse call
func ParseGetCreateBridgeResponse(rsp *http.Response) (*GetCreateBridgeResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetCreateBridgeResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest CreateBridgeEntryDto
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /api)
	GetHello(ctx echo.Context) error

	// (POST /api/sequencer/create-bridge/sign/{id})
	SignCreateBridge(ctx echo.Context, id string) error

	// (GET /api/sequencer/create-bridge/{id})
	GetCreateBridge(ctx echo.Context, id string) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetHello converts echo context to params.
func (w *ServerInterfaceWrapper) GetHello(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetHello(ctx)
	return err
}

// SignCreateBridge converts echo context to params.
func (w *ServerInterfaceWrapper) SignCreateBridge(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.SignCreateBridge(ctx, id)
	return err
}

// GetCreateBridge converts echo context to params.
func (w *ServerInterfaceWrapper) GetCreateBridge(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetCreateBridge(ctx, id)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/api", wrapper.GetHello)
	router.POST(baseURL+"/api/sequencer/create-bridge/sign/:id", wrapper.SignCreateBridge)
	router.GET(baseURL+"/api/sequencer/create-bridge/:id", wrapper.GetCreateBridge)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/7yWQU/cPhDFv0o0//8xbEJ7yxEolBapUkHqAe3B6wxZ08Q29gSxWvm7V57skixJRShV",
	"LxAl4+c383u2dgvSNNZo1OSh2IKXa2wEP546FIQnTpUVftLkNmdk4nvrjEVHCrlKlfEvbSxCAZ6c0hWE",
	"FJT3rdLV6VoofWaMG4rdOKG9kKSMfnXtDX/cAuq2geIWnpyFFPCxgWU6Xlkb+fNPdx2ufcuuIQWHD61y",
	"WMZSVcKE1nxrE+3Pn2bvzqzuUVLs61pVegDxOz606GkM0qtKY3k5n5uo6293UNxu4X+Hd1DAf1mfpWwX",
	"pOyaZQdL9wbCMqS7Ta/mY3v/pi94vc1B+sYx/Q7IpLkREiGlaTV/aMTTFeqK1lAc53meT4Tftqtaya+4",
	"mVkfOxHUOpxV/2Jse2tDmaGFceNxR5StU7S5jpi6FlcoHLr+6dy4RhAU8OXHTRTnSij2dc+qayILIYoq",
	"fcfXkjSahIzDCimQopqXMZEjHyesJQs8ovMcJsgX+eI4TsJY1MIqKODjIl/ksRFBa/aX8fstVMgYIh0R",
	"mV2WUMAF0mesawNxNt4a7bumPuR5/Feil07ZLroQ3YaUBbNnP5nk4Bx1PrM4y2yrysBZMF0mDmVienwi",
	"dNLqLopJJ5F0Egn1uUpWm4Svo0PXUWGYV27XiQYJneejpeJGcQSQghY8f9bpA0CuxR0dMXGbhmVXjJ5O",
	"TLnZ48Euy8LaWkk2lN377lz3Uq+d64m7LBymM5oLIyTHk0hSIFF5vgieM7J8ldMe0S4Vh6rnSpfvI3SB",
	"9E8AjSP7VyhN/nBgRnPHH8KvAAAA///iEcIYmAgAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
